from datetime import datetime

def generate_report(image_result, tabular_result, nlp_result, risk) -> dict:
    """
    Generate a plain-English clinical summary from all module outputs.
    Returns both a short summary and a detailed report.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Build short summary
    short_summary = (
        f"AI Risk Score: {risk['score']}/100 — {risk['category']}. "
        f"Imaging suggests {image_result['label']} "
        f"({image_result['probability']*100:.1f}%). "
        f"Clinical features indicate {tabular_result['label']} "
        f"({tabular_result['probability']*100:.1f}%). "
        f"Symptom analysis: {nlp_result['label']} "
        f"({nlp_result['risk_signal']}%). "
        f"Recommendation: {risk['action']}"
    )

    # Build detailed report
    detailed_report = f"""
BREAST CANCER AI SCREENING REPORT
===================================
Generated : {timestamp}
Risk Score : {risk['score']} / 100
Category   : {risk['category']}
Urgency    : {risk['urgency']} / 5
===================================

MODULE BREAKDOWN
----------------
1. IMAGING ANALYSIS (Weight: 45%)
   Result     : {image_result['label']}
   Probability: {image_result['probability']*100:.2f}%
   Confidence : {image_result.get('confidence', 'N/A')}

2. CLINICAL FEATURES (Weight: 40%)
   Result     : {tabular_result['label']}
   Probability: {tabular_result['probability']*100:.2f}%
   Confidence : {tabular_result.get('confidence', 'N/A')}%

3. SYMPTOM ANALYSIS (Weight: 15%)
   Result     : {nlp_result['label']}
   Risk Signal: {nlp_result['risk_signal']}%
   Confidence : {nlp_result['confidence']}

===================================
RECOMMENDATION
--------------
{risk['action']}

===================================
DISCLAIMER
----------
This report is generated by an AI screening tool
for educational and research purposes only.
It is NOT a medical diagnosis. Final clinical
decisions must be made by a qualified physician.
===================================
"""

    return {
        'short': short_summary,
        'detailed': detailed_report,
        'timestamp': timestamp
    }
